const datos: { [key: number]: string } = {
    0: "status", 
    1: "Temperature",
    2: "Temperature #2",
    3: "Relative Humidity",
    4: "Atmospheric Pressure",
    5: "Light",
    6: "Soil Moisture",
    7: "Soil Moisture #2",
    8: "Soil Resistance",
    9: "Soil Resistance #2",
    10: "Oxygen",
    11: "Carbon Dioxide",
    12: "Wind Speed",
    13: "Rainfall",
    14: "Wind Direction",
    15: "Motion",
    16: "Voltage",
    17: "Voltage #2",
    18: "Current",
    19: "Current #2",
    20: "Iterations",
    21: "Latitude",
    22: "GPS Longitude",
    23: "GPS Altitude",
    24: "GPS HDOP",
    25: "Altura del suelo" 
};